### ISSUE TITLE
Readability: Make the code PEP8 compliant

### ISSUE THREAD

**Issue by palash25** [itsmepiyush2/Movie-Recommender#2]
Hi, I just stumbled upon this today.

One of the best practices that are followed in Python development is following [PEP8 guidelines](https://www.python.org/dev/peps/pep-0008/)

You can do this manually although there are linters available for this too.

**Comment by piyushmishra12** [comment]
Thanks for the insight! Didn't think of that prior to this. I will most certainly work on that.

**Comment by piyushmishra12** [comment]
Did it.
